# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7.35
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
